### ISSUE TITLE
Add examples and use-cases

### ISSUE THREAD

**Issue by vissarion** [GeomScale/dingo#15]
`dingo` currently has a limited number of examples of use, mainly in `tests`. 

Create an `example` directory and add analysis for networks from public datasets e.g. http://bigg.ucsd.edu

Other use cases using FVA, FBA or sampling for metabolic models are welcome to be added there too.

**Comment by pramitsahoo** [comment]
Hello @vissarion  
                 I am a complete beginner and i want to contibute but i am unable to setup this dingo project locally . can you please help me?

**Comment by hariszaf** [comment]
Hi @PramitSahoo. Did you try to follow the steps described [here](https://colab.research.google.com/drive/1AdXCo6tMBV4lPDYWWOXhzcM0wg30OOIx?usp=sharing)?

**Comment by vissarion** [comment]
It seems that [this notebook](https://github.com/GeomScale/dingo/blob/develop/tutorials/dingo_tutorial.ipynb) resolves this issue.
