### ISSUE TITLE
Read `.xml` models 

### ISSUE THREAD

**Issue by hariszaf** [GeomScale/dingo#26]
To address the challenges that come along with the metabolic network reconstruction process, 
the metabolic modeling community has adopted the Systems Biology Markup Language (SBML) 
to a great extent. 

Therefore, most metabolic models are in a `.xml` format and this is the reason that supporting 
this format would benefit `dingo` the most. 

To this end, `dingo` could make use of the [`libsbml`](http://model.caltech.edu/software/libsbml/5.18.0/docs/formatted/python-api/) library via its Python interface.

**Comment by Ghostfreak-077** [comment]
Sir, I am a pythonist and I would like to solve this issue. but, I am not much into networks, so can you guide me to solve the issue.

**Comment by himanshuParashar0101** [comment]
kindly assign this issue to me

**Comment by vissarion** [comment]
Please go ahead and submit a PR.

**Comment by hariszaf** [comment]
Hello there. 
Was there any progress reg. this issue? 
Thanks a lot!
