### ISSUE TITLE
For Begginer

### ISSUE THREAD

**Issue by nikdantani** [GeomScale/dingo#30]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nikdantani** [comment]
Mention this how to complete PR challenge of Hacktoberfest

**Comment by vissarion** [comment]
@nikdantani Please select an issue https://github.com/GeomScale/dingo/issues with the Hacktoberfest label and open a PR that fixes it. 

More info:

https://blog.shahednasser.com/how-to-participate-in-hacktoberfest-2021/
https://opensource.guide/how-to-contribute/
https://hacktoberfest.digitalocean.com/resources/beginners
