### ISSUE TITLE
Error importing MetabolicNetwork class from dingo package in Google Colab (GSoC 2023)

### ISSUE THREAD

**Issue by samadpls** [GeomScale/dingo#60]
**Describe the bug**
When running the cell provided in the README of the "https://github.com/GeomScale/dingo" project on Google Colab, an error message appears stating that the name 'MetabolicNetwork' cannot be imported from 'dingo' at an unknown location.

**To Reproduce**

1. Go to the following link: "https://colab.research.google.com/github/GeomScale/dingo/blob/develop/tutorials/dingo_tutorial.ipynb"
2. Run all cells until the point where it is written "from dingo import MetabolicNetwork".

**Expected behavior**
The code should be able to import the MetabolicNetwork class from the dingo package without any errors.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Google Chrome
- Version:  110.0.5481.178 (Official Build) (64-bit)

**Additional context**
I am working on task 1 for applying to GSoC on this project and I need assistance in resolving this issue so that I can complete my task.

**Comment by hariszaf** [comment]
Hi @samadpls thanks for mentioning this. 

Make sure of the Python version your colab notebook uses and edit the
`.path.append("/root/.local/lib/python3.7/site-packages/"))` line accordingly.
