### ISSUE TITLE
sample asking for a min/max value of the objective function 

### ISSUE THREAD

**Issue by hariszaf** [GeomScale/dingo#65]
One might need to sample using not a fixed value for the objective function but asking its value to be at least or at the most $c$.

It would be really useful for the flux sampling function to provide this option.

**Comment by vissarion** [comment]
If I understand correctly your inquiry, for an objective function $a$, one can add $ax\leq c$ (or $ax\geq c$) as a new inequality and sample from the new polytope.

**Comment by hariszaf** [comment]
Exactly! This was also needed in Régimbeau et al. paper you mentioned in #64 .

**Comment by hariszaf** [comment]
Issue solved in #9 and is able setting the `set_opt_percentage` argument.
