### ISSUE TITLE
Modify model's medium

### ISSUE THREAD

**Issue by TolisChal** [GeomScale/dingo#74]
Modify both MetabolicNetwork and PolytopeSampler classes to change the bounds of the medium reactions

**Comment by hariszaf** [comment]
use a dictionary as in cobra 
```{'EX_co2_e': 1000.0,
 'EX_glc__D_e': 10.0,
 'EX_h_e': 1000.0,
 'EX_h2o_e': 1000.0,
 'EX_nh4_e': 1000.0,
 'EX_o2_e': 1000.0,
 'EX_pi_e': 1000.0}
 ```

and an internal one with the reactions' indexes
