### ISSUE TITLE
Consider renaming `biomass_function` routine

### ISSUE THREAD

**Issue by hariszaf** [GeomScale/dingo#82]
Should we rename [this](https://github.com/GeomScale/dingo/blob/aaae4ae63f432da45eb0f4363a92767ba537a074/dingo/MetabolicNetwork.py#L146) to `objective function` 	?
This way when we are not using the biomass function as objective we will not have misunderstandings.

**Comment by hritikb** [comment]
I suppose this only involves renaming the `biomass_function` to `objective_function` and then modifying the calls to `biomass_function` accordingly? If so, I can make these changes.

**Comment by hariszaf** [comment]
Thanks a lot @hritikb for your support. 
Of course you may go ahead with this task, but please let the `biomass_index` as is, so people can always find its index easy. 
Also make sure you rename this variable through the whole repo, including tests and tutorials.

**Comment by hritikb** [comment]
I have opened a PR for this (#97). You may please take a look.
