### ISSUE TITLE
Update README installation instructions to be more user friendly

### ISSUE THREAD

**Issue by rkstu** [GeomScale/dingo#89]
I encountered difficulties setting up the Dingo project completely for the first time and discussed the issues on Gitter. After repeatedly configuring the entire project over the past few weeks, particularly while addressing issue #83, I am convinced that making minor modifications to the README file can greatly streamline the setup process, ultimately saving considerable time and effort for new users

**Challenges Faced:**
* Version incompatibility due to Python and project-dependent libraries.
* Unclear instructions on the Poetry version for setup.

 ![dingo_poetry](https://github.com/GeomScale/dingo/assets/93584728/a5fe1b07-fde9-4741-9217-6153c37af973)

**Proposed Change in instructions:**
* Make sure the Python version is 3.8 [workflows](https://github.com/GeomScale/dingo/blob/aaae4ae63f432da45eb0f4363a92767ba537a074/.github/workflows/ubuntu.yml#L19)

* Install a specific version of poetry [workflows](https://github.com/GeomScale/dingo/blob/aaae4ae63f432da45eb0f4363a92767ba537a074/.github/workflows/ubuntu.yml#L38)
```
curl -sSL https://install.python-poetry.org | python3 - --version 1.3.2
```
* Install the dependencies for the PySPQR library using
```
sudo apt-get update -y
sudo apt-get install -y libsuitesparse-dev
```

**Proposal for trial** 
For a quick and hassle-free Dingo project trial, consider using GitHub Codespaces. It provides an instant cloud-based development environment with limited free usage every month. Regardless of your operating system, you can set up and run experiments in under 10 minutes(depends on internet speed), thanks to its streamlined installation process. Additionally, consider utilizing another tab to include screenshots with installation steps and examples, which are mostly done.

**Comment by vfisikop** [comment]
Thanks, please feel free to open a PR with those changes.

**Comment by vfisikop** [comment]
Please also consult the information in this issue https://github.com/GeomScale/dingo/issues/77 regarding incompatibility of versions.

**Comment by vikasgrewal16** [comment]
Is this issue closed or still open? @rkstu @vfisikop

**Comment by vfisikop** [comment]
It is open but there is a PR that is in progress https://github.com/GeomScale/dingo/pull/91 
In general you are free to open your PR for the same issue but I do not recommend it for such a simple issue (it is only a documentation enhancement).

**Comment by vfisikop** [comment]
Closed by https://github.com/GeomScale/dingo/pull/91
